# Generated by Django 6.0.5 on 2026-06-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
