# Generated by Django 6.0.5 on 2026-06-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_notes_is_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
